module.exports = {
    "STANDINGS_UPDATED": "STANDINGS_UPDATED",
    "GAMES_UPDATED": "GAMES_UPDATED",
    "QUEUE_UPDATED": "QUEUE_UPDATED",
    "GAME_QUEUED": "GAME_QUEUED",
    "GAME_ENDED": "GAME_ENDED",
    "GAME_STARTED": "GAME_STARTED",
    "GOAL_SCORED": "GOAL_SCORED",
    "GAME_GOALS_LOADED": "GAME_GOALS_LOADED",
    "PLAYERS_LOADED": "PLAYERS_LOADED",
    "MODAL_SHOW_GAME": "MODAL_SHOW_GAME"
}