module.exports = {
    "STANDINGS_UPDATED": "STANDINGS_UPDATED",
    "GAMES_UPDATED": "GAMES_UPDATED",
    "QUEUE_UPDATED": "QUEUE_UPDATED",
    "GAME_QUEUED": "GAME_QUEUED",
    "GAME_ENDED": "GAME_ENDED",
    "GAME_STARTED": "GAME_STARTED",
    "GOAL_SCORED": "GOAL_SCORED"
}